/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardChatRouteImport } from './routes/dashboard.chat'
import { Route as DashboardAccountIndexRouteImport } from './routes/dashboard.account.index'
import { Route as AccountConnectTelegramRouteImport } from './routes/account.connect.telegram'
import { Route as DashboardAccountConnectTelegramRouteImport } from './routes/dashboard.account.connect.telegram'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountIndexRoute = DashboardAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => DashboardRoute,
} as any)
const AccountConnectTelegramRoute = AccountConnectTelegramRouteImport.update({
  id: '/connect/telegram',
  path: '/connect/telegram',
  getParentRoute: () => AccountRoute,
} as any)
const DashboardAccountConnectTelegramRoute =
  DashboardAccountConnectTelegramRouteImport.update({
    id: '/account/connect/telegram',
    path: '/account/connect/telegram',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/account/': typeof AccountIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/account/connect/telegram': typeof AccountConnectTelegramRoute
  '/dashboard/account/': typeof DashboardAccountIndexRoute
  '/dashboard/account/connect/telegram': typeof DashboardAccountConnectTelegramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/account': typeof AccountIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/account/connect/telegram': typeof AccountConnectTelegramRoute
  '/dashboard/account': typeof DashboardAccountIndexRoute
  '/dashboard/account/connect/telegram': typeof DashboardAccountConnectTelegramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/account/': typeof AccountIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/account/connect/telegram': typeof AccountConnectTelegramRoute
  '/dashboard/account/': typeof DashboardAccountIndexRoute
  '/dashboard/account/connect/telegram': typeof DashboardAccountConnectTelegramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/chat'
    | '/dashboard'
    | '/login'
    | '/notifications'
    | '/settings'
    | '/dashboard/chat'
    | '/dashboard/settings'
    | '/account/'
    | '/dashboard/'
    | '/account/connect/telegram'
    | '/dashboard/account/'
    | '/dashboard/account/connect/telegram'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/login'
    | '/notifications'
    | '/settings'
    | '/dashboard/chat'
    | '/dashboard/settings'
    | '/account'
    | '/dashboard'
    | '/account/connect/telegram'
    | '/dashboard/account'
    | '/dashboard/account/connect/telegram'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/chat'
    | '/dashboard'
    | '/login'
    | '/notifications'
    | '/settings'
    | '/dashboard/chat'
    | '/dashboard/settings'
    | '/account/'
    | '/dashboard/'
    | '/account/connect/telegram'
    | '/dashboard/account/'
    | '/dashboard/account/connect/telegram'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account/': {
      id: '/dashboard/account/'
      path: '/account'
      fullPath: '/dashboard/account/'
      preLoaderRoute: typeof DashboardAccountIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/account/connect/telegram': {
      id: '/account/connect/telegram'
      path: '/connect/telegram'
      fullPath: '/account/connect/telegram'
      preLoaderRoute: typeof AccountConnectTelegramRouteImport
      parentRoute: typeof AccountRoute
    }
    '/dashboard/account/connect/telegram': {
      id: '/dashboard/account/connect/telegram'
      path: '/account/connect/telegram'
      fullPath: '/dashboard/account/connect/telegram'
      preLoaderRoute: typeof DashboardAccountConnectTelegramRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AccountRouteChildren {
  AccountIndexRoute: typeof AccountIndexRoute
  AccountConnectTelegramRoute: typeof AccountConnectTelegramRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountIndexRoute: AccountIndexRoute,
  AccountConnectTelegramRoute: AccountConnectTelegramRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface DashboardRouteChildren {
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAccountIndexRoute: typeof DashboardAccountIndexRoute
  DashboardAccountConnectTelegramRoute: typeof DashboardAccountConnectTelegramRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardChatRoute: DashboardChatRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAccountIndexRoute: DashboardAccountIndexRoute,
  DashboardAccountConnectTelegramRoute: DashboardAccountConnectTelegramRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
